receivers:
  awsecscontainermetrics:

processors:
  filter:
    metrics:
      include:
        match_type: regexp
        metric_names:
          - ecs.task.memory.reserved
          - ecs.task.memory.utilized
          - container.memory.reserved
          - container.memory.utilized
          - ecs.task.cpu.reserved
          - ecs.task.cpu.utilized
          - container.cpu.reserved
          - container.cpu.utilized
          - ecs.task.network.rate.rx
          - ecs.task.network.rate.tx
          - ecs.task.storage.read_bytes
          - ecs.task.storage.write_bytes
          - ecs.task.network.io.usage.rx_errors
          - ecs.task.network.io.usage.rx_dropped
          - ecs.task.network.io.usage.tx_errors
          - ecs.task.network.io.usage.tx_dropped
  metricstransform:
    transforms:
      - include: ecs.task.memory.utilized
        action: update
        new_name: ECSTaskMemoryUtilized
      - include: ecs.task.memory.reserved
        action: update
        new_name: ECSTaskMemoryReserved
      - include: container.memory.utilized
        action: update
        new_name: ContainerMemoryUtilized
      - include: container.memory.reserved
        action: update
        new_name: ContainerMemoryReserved
      - include: ecs.task.cpu.utilized
        action: update
        new_name: ECSTaskCpuUtilized
      - include: ecs.task.cpu.reserved
        action: update
        new_name: ECSTaskCpuReserved
      - include: container.cpu.utilized
        action: update
        new_name: ContainerCpuUtilized
      - include: container.cpu.reserved
        action: update
        new_name: ContainerCpuReserved
      - include: ecs.task.network.rate.rx
        action: update
        new_name: ECSTaskNetworkRxBytes
      - include: ecs.task.network.rate.tx
        action: update
        new_name: ECSTaskNetworkTxBytes
      - include: ecs.task.storage.read_bytes
        action: update
        new_name: ECSTaskStorageReadBytes
      - include: ecs.task.storage.write_bytes
        action: update
        new_name: ECSTaskStorageWriteBytes
      - include: ecs.task.network.io.usage.rx_errors
        action: update
        new_name: ECSTaskNetworkRxErrors
      - include: ecs.task.network.io.usage.rx_dropped
        action: update
        new_name: ECSTaskNetworkRxDroppedPackets
      - include: ecs.task.network.io.usage.tx_errors
        action: update
        new_name: ECSTaskNetworkTxErrors
      - include: ecs.task.network.io.usage.tx_dropped
        action: update
        new_name: ECSTaskNetworkTxDroppedPackets
  resource:
    attributes:
      - key: ClusterName
        from_attribute: aws.ecs.cluster.name
        action: insert
      - key: aws.ecs.cluster.name
        action: delete
      - key: ServiceName
        from_attribute: aws.ecs.service.name
        action: insert
      - key: aws.ecs.service.name
        action: delete
      - key: TaskId
        from_attribute: aws.ecs.task.id
        action: insert
      - key: aws.ecs.task.id
        action: delete
      - key: TaskDefinitionFamily
        from_attribute: aws.ecs.task.family
        action: insert
      - key: aws.ecs.task.family
        action: delete
      - key: ContainerName
        from_attribute: container.name
        action: insert
      - key: container.name
        action: delete


exporters:
  influxdb:
    endpoint: http://ec2-13-215-209-202.ap-southeast-1.compute.amazonaws.com:8086 # This is a test instance
    bucket: test
    token: password
  awsemf:
    namespace: 'ECS/ContainerInsights/Opentelemetry'
    log_group_name:  '/aws/ecs/containerinsights/{ClusterName}/performance'
    log_stream_name: '{TaskId}'
    resource_to_telemetry_conversion:
      enabled: true
    dimension_rollup_option: NoDimensionRollup
    metric_declarations:
      - dimensions: [[ClusterName, TaskDefinitionFamily, TaskId]]
        metric_name_selectors:
          - ECSTaskMemoryUtilized
          - ECSTaskMemoryReserved
          - ECSTaskCpuUtilized
          - ECSTaskCpuReserved
          - ECSTaskNetworkRxBytes
          - ECSTaskNetworkTxBytes
          - ECSTaskStorageReadBytes
          - ECSTaskStorageWriteBytes
          - ECSTaskNetworkRxErrors
          - ECSTaskNetworkRxDroppedPackets
          - ECSTaskNetworkTxErrors
          - ECSTaskNetworkRxDroppedPackets
      - dimensions: [[ClusterName, TaskDefinitionFamily, TaskId, ContainerName]]
        metric_name_selectors:
          - ContainerMemoryUtilized
          - ContainerMemoryReserved
          - ContainerCpuUtilized
          - ContainerCpuReserved

service:
  pipelines:
    metrics/ecs_infra:
      receivers: [awsecscontainermetrics]
      processors: [filter, metricstransform, resource]
      exporters: [influxdb]